### PR TITLE
Ability to disable martor admin css file when using customized admins like graphelli and others

### PR DESCRIPTION
**Pull request by oasisMystre**
When using custom admins like Grappelli martor admin CSS should be disabled using 

```MARTOR_ENABLE_ADMIN_CSS=False # default is true```

### CODE REVIEW

**Comment by agusmakmun** [comment]
hello @oasisMystre, thank you for making this changes.. 
can you please elaborate why these 2 css files are changed?

```
martor/static/martor/css/martor.bootstrap.css
martor/static/plugins/css/bootstrap.min.css
```

I think both is not related right? can you please revert back that files?

**Comment by oasisMystre** [comment]
Bootstrap use a !important to add style to <a> tag I can't disable bootstrap since the markdown widget depends on it so I have to remove styling for <a> tag since it works fine without it.

I can revert if you want me too, I'm using this library for a production project will work with our own fork.


Will add the documentation for the changes, thanks for this amazing library really helped 👊

**Comment by agusmakmun** [comment]
@oasisMystre can you please revert the .css changes? so we can push it immediately.. again thank you so much for making this changes, really appreciate it.. 👍

**Comment by oasisMystre** [comment]
Okay

**Pull request merged**
