### PR TITLE
Drop support for Python 3.6, enable support for Markdown 3.4

### PR DESCRIPTION
**Pull request by tomaszn**
There are incompatibilities with Markdown 3.4.

@agusmakmun Can you take a look at these?
https://github.com/Python-Markdown/markdown/blob/master/docs/change_log/release-3.4.md

I suggest releasing this as `v1.7.0` (bump the minor version).

### CODE REVIEW

**Comment by agusmakmun** [comment]
hello @tomaszn, thank you for making this changes.. can we somehow support the python 3.6 as well?
let say, for python 3.6 will be use Markdown < 3.4, then for the higher version will use Markdown < 3.5

**Comment by DerDennisOP** [comment]
image

You need to remove the "md_globals" input parameter from every Extension Class.
Also make sure you use the .register function:
`md.inlinePatterns["autolink"] = UrlizePattern(URLIZE_RE, md)` -> `md.inlinePatterns.register((URLIZE_RE, md), 'autolink', 100)`

**Comment by DerDennisOP** [comment]
Also Python 3.6 is depricated now for almost 5 years and security support ended 1 year ago. I don't think we need Python 3.6 support

**Comment by agusmakmun** [comment]
Hello @tomaszn sorry for closing this PR, this fixes is alraedy in this commit:

https://github.com/agusmakmun/django-markdown-editor/commit/82f9dadc61a91c0e380fe2851da0f3e908fce639

**Pull request closed without merging**
